[project]
name = "sdf_pipeline"
version = "0.1.0"

[project.optional-dependencies]
dev = [
    "black",
    "mypy",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = [
    "tests",
]
addopts = "-v"