[project]
name = "sdf_pipeline"
version = "1.1.0"
dependencies = ["pydantic >= 2.6.4"]

[project.optional-dependencies]
dev = ["pytest"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"
